server:
  port: 10002

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr:http://nacos.jupiter.com}
        username: ${nacos.username:nacos}
        password: ${nacos.password:nacos}
        namespace: ${spring.profiles.active:dev}
      config:
        server-addr: ${nacos.server-addr:http://nacos.jupiter.com}
        username: ${nacos.username:nacos}
        password: ${nacos.password:nacos}
        namespace: ${spring.profiles.active:dev}
        file-extension: yml
        shared-configs: application.yml
        prefix: ${spring.application.name}
  config:
    import:
      - nacos:application.yml
      - nacos:${spring.application.name}.yml




  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:${server.port}/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:${server.port}/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true